### ISSUE TITLE
Feature Request: Delete Nodes older than X days based on NodeType

### ISSUE THREAD

**Issue by paavo** [jvm-tech/JvMTECH.Anonymizer#1]
As documented [here](https://github.com/jvm-tech/JvMTECH.Anonymizer) for custom domainModels, i'd love to have an easy way to delete NodeTypes with similar parameters like:

```
JvMTECH:
  Anonymizer:
    nodeTypes:

      'Your.Vendor:Your.NodeType':
        dateTimeFilter: # optional
          propertyName: 'creationDateTime'
          olderThan: -90 # days
```

Using `Neos\ContentRepository\Domain\Model\Node` as domainModel could work somehow too...
But no idea how to separate different Nodetypes 🤔
